<?php

/**
 * Implements hook_views_api()
 */
function views_infinite_ajax_scroll_views_api() {
  return array(
    'api' => 3,
	'path' => drupal_get_path('modules', 'views_infinite_ajax_scroll') . '/views';
  );
}

/**
 * Implementation of hook_theme().
 */
function views_infinite_ajax_scroll_theme() {
  return array(
    'views_infinite_ajax_scroll' => array(
      'variables' => array('tags' => array(), 'quantity' => 10, 'element' => 0, 'parameters' => array()),
      'pattern' => 'views_infinite_ajax_scroll_pager__',
    ),
  );
}

function theme_views_infinite_ajax_scroll($vars) {
  global $pager_page_array, $pager_total;

  $tags = $vars['tags'];
  $element = $vars['element'];
  $parameters = $vars['parameters'];

  $pager_classes = array('pager', 'pager-ias');

  $li_next = theme('pager_next',
    array(
      'text' => '&nbsp;',
      'element' => $element,
      'interval' => 1,
      'parameters' => $parameters,
    )
  );
  if (empty($li_next)) {
    $li_next = '&nbsp;';
    $pager_classes[] = 'pager-ias-empty';
  }
  // Compatibility with tao theme's pager
  elseif (is_array($li_next) && isset($li_next['title'], $li_next['href'], $li_next['attributes'], $li_next['query'])) {
    $li_next = l($li_next['title'], $li_next['href'], array('attributes' => $li_next['attributes'], 'query' => $li_next['query']));
  }

  if ($pager_total[$element] > 1) {
    $items[] = array(
      'class' => array('pager-next'),
      'data' => $li_next,
    );
    return theme('item_list',
      array(
        'items' => $items,
        'title' => NULL,
        'type' => 'ul',
        'attributes' => array('class' => $pager_classes),
      )
    );
  }
}


/**
 * Check for the library and return the appropriate scope.
 */
function views_infinite_ajax_scroll_check_library() {
  // @TODO: Cache the result.
  if (function_exists('libraries_get_path') && file_exists(libraries_get_path('infinite-ajax-scroll') . '/jquery-ias.min.js') === TRUE) {
    // Library has been installed correctly, so use it.
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_views_pre_render().
 *
 * Load js file only if ajax is disabled.
 */
function views_infinite_ajax_scroll_views_pre_render(&$view) {
  if ($view->use_ajax) {
    return;
  }

  $ias_library = views_infinite_ajax_scroll_check_library(); // Check for ias library.
  if (isset($view->query->pager->plugin_name) && $view->query->pager->plugin_name == 'ias' && $ias_library) {
	dpm($view->query->pager->options);
	// Set values initiating ias
	$ias_settings = array(
	  'id' => '.view-id-clone_of_code_snippets',
	  'container' => '.views-content',
	  'item' => '.views-row',
	  'pagination' => 'ul.pager-ias',
	  'next' => 'li.pager-next a',
	  'delay' => 500,
	  'negativeMargin' => 300,
	); 
	drupal_add_js(array('view_infinite_ajax_scroll' => $ias_settings), 'setting');
	
	drupal_add_js(libraries_get_path('infinite-ajax-scroll') . '/' . '/jquery-ias.min.js');
    drupal_add_js(drupal_get_path('module', 'views_infinite_ajax_scroll') . '/js/views_infinite_ajax_scroll.js');
  }
}